# Generated by Django 4.2.1 on 2023-09-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название урока')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка на видео')),
                ('video_duration', models.PositiveIntegerField(verbose_name='Длительность видео')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(max_length=50, unique=True, verbose_name='Логин'),
        ),
    ]
