# Generated by Django 4.2.1 on 2023-09-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_last_seen_datetime_lessonviews_datetime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonviews',
            unique_together={('lesson', 'user', 'datetime')},
        ),
    ]
