# Generated by Django 4.2.1 on 2023-09-28 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_lessonviews_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users', unique=True),
        ),
    ]
