# Generated by Django 4.2.1 on 2023-09-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_access_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название продукта'),
        ),
    ]
