# Generated by Django 4.2.1 on 2023-09-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_products_product_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonviews',
            unique_together={('lesson', 'user')},
        ),
    ]
