# Generated by Django 4.2.1 on 2023-09-29 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_lessonviews_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAllProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Время просмотра')),
                ('status', models.BooleanField(default=False, verbose_name='Статус просмотра')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lessons')),
            ],
        ),
    ]
