# Generated by Django 4.2.1 on 2023-09-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_apiallproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='available_products',
            field=models.ManyToManyField(to='main.products'),
        ),
    ]
