# Generated by Django 4.2.1 on 2023-09-29 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_access_available_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='available_products',
        ),
        migrations.AddField(
            model_name='access',
            name='available_products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.products'),
        ),
    ]
