# Generated by Django 4.2.1 on 2023-09-29 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_access_available_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users'),
        ),
        migrations.AlterUniqueTogether(
            name='access',
            unique_together={('user', 'available_products')},
        ),
    ]
