# Generated by Django 4.2.1 on 2023-09-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_apicurrentproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIProductStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_viewing_count', models.PositiveIntegerField(verbose_name='Кол-во просмотренных уроков от всех учеников')),
                ('lessons_viewing_time', models.PositiveIntegerField(verbose_name='Кол-во потраченного времени на просмотр уроков')),
                ('users_count', models.PositiveIntegerField(verbose_name='Кол-во учеников занимающихся на продукте')),
                ('product_purchase_percent', models.FloatField(verbose_name='Процент приобретения продукта')),
            ],
        ),
    ]
