# Generated by Django 4.2.1 on 2023-09-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_apiproductstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiproductstatistics',
            name='name',
            field=models.CharField(default='Без названия', max_length=250, verbose_name='Название продукта'),
        ),
    ]
